"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, BarChart3, Bell, CalendarDays, ChevronDown, CircleHelp, LayoutDashboard, Menu, Plus, Receipt, Search, Settings, Sparkles, Trash2, Wallet, X } from "lucide-react";

type Expense = { id: number; title: string; category: string; date: string; amount: number; icon: string; color: string };
const starterExpenses: Expense[] = [
  { id: 1, title: "Whole Foods Market", category: "Food & dining", date: "2026-09-22", amount: 84.32, icon: "W", color: "mint" },
  { id: 2, title: "Monthly rent", category: "Housing", date: "2026-09-18", amount: 1250, icon: "H", color: "blue" },
  { id: 3, title: "Metro transit pass", category: "Transport", date: "2026-09-15", amount: 65, icon: "M", color: "orange" },
  { id: 4, title: "Figma subscription", category: "Subscriptions", date: "2026-09-12", amount: 15, icon: "F", color: "pink" },
  { id: 5, title: "Coffee & catch-up", category: "Food & dining", date: "2026-09-08", amount: 12.5, icon: "C", color: "mint" },
];
const categories = [{ name: "Housing", amount: 1250, percent: 57, color: "#87a7ff" }, { name: "Food & dining", amount: 96.82, percent: 5, color: "#f5a77b" }, { name: "Transport", amount: 65, percent: 3, color: "#9bdfc3" }, { name: "Subscriptions", amount: 15, percent: 1, color: "#e9a9bd" }];
const formatMoney = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);

export default function Home() {
  const [expenses, setExpenses] = useState<Expense[]>(starterExpenses);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [newExpense, setNewExpense] = useState({ title: "", category: "Food & dining", amount: "", date: "2026-09-24" });
  const [hasLoadedExpenses, setHasLoadedExpenses] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const saved = window.localStorage.getItem("pocket-ledger-expenses"); if (saved) setExpenses(JSON.parse(saved)); setHasLoadedExpenses(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (hasLoadedExpenses) window.localStorage.setItem("pocket-ledger-expenses", JSON.stringify(expenses)); }, [expenses, hasLoadedExpenses]);
  const filteredExpenses = useMemo(() => expenses.filter((expense) => expense.title.toLowerCase().includes(query.toLowerCase()) || expense.category.toLowerCase().includes(query.toLowerCase())), [expenses, query]);
  const totalSpent = expenses.reduce((total, expense) => total + expense.amount, 0);
  const addExpense = (event: React.FormEvent) => { event.preventDefault(); if (!newExpense.title || !newExpense.amount) return; const colorMap: Record<string, string> = { Housing: "blue", "Food & dining": "mint", Transport: "orange", Subscriptions: "pink", Other: "purple" }; setExpenses([{ id: Date.now(), title: newExpense.title, category: newExpense.category, date: newExpense.date, amount: Number(newExpense.amount), icon: newExpense.title[0].toUpperCase(), color: colorMap[newExpense.category] || "purple" }, ...expenses]); setNewExpense({ title: "", category: "Food & dining", amount: "", date: "2026-09-24" }); setIsModalOpen(false); };
  return <main className="app-shell">
    <aside className={`sidebar ${isMenuOpen ? "sidebar-open" : ""}`}><div className="brand"><span className="brand-mark"><Wallet size={19} /></span><span>Pocket Ledger</span></div><nav className="nav-list" aria-label="Primary navigation"><a className="nav-item active" href="#overview"><LayoutDashboard size={18} /> Overview</a><a className="nav-item" href="#transactions"><Receipt size={18} /> Transactions <span className="nav-count">12</span></a><a className="nav-item" href="#insights"><BarChart3 size={18} /> Insights</a></nav><div className="nav-label">Workspace</div><nav className="nav-list"><a className="nav-item" href="#settings"><Settings size={18} /> Settings</a><a className="nav-item" href="#help"><CircleHelp size={18} /> Help center</a></nav><div className="sidebar-bottom"><div className="upgrade-card"><Sparkles size={18} /><strong>Make money feel simple.</strong><p>Set a goal and keep your good habits going.</p><button>View your plan <ArrowUpRight size={14} /></button></div><div className="profile"><span className="avatar">AJ</span><span><strong>Alex Johnson</strong><small>Personal workspace</small></span><ChevronDown size={15} /></div></div></aside>
    <section className="main-content"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setIsMenuOpen(!isMenuOpen)} aria-label="Toggle menu"><Menu size={20} /></button><div className="breadcrumb">Workspace <span>/</span> Overview</div><div className="top-actions"><div className="search-box"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search expenses" /></div><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button><button className="button-primary top-add" onClick={() => setIsModalOpen(true)}><Plus size={16} /> Add expense</button></div></header>
      <div className="content-wrap" id="overview"><div className="intro"><div><p className="eyebrow">Tuesday, September 24, 2026</p><h1>Good morning, Alex <span>✦</span></h1><p className="intro-copy">Here&apos;s the shape of your spending this month.</p></div><button className="date-button"><CalendarDays size={16} /> September 2026 <ChevronDown size={15} /></button></div>
        <div className="stats-grid"><div className="stat-card dark-card"><div className="stat-heading"><span>Total spent</span><ArrowDownLeft size={17} /></div><strong>{formatMoney(totalSpent)}</strong><div className="stat-foot"><span className="positive">↓ 8.4%</span> <span>vs last month</span></div><div className="sparkline">{Array.from({ length: 12 }, (_, index) => <span key={index} />)}</div></div><div className="stat-card"><div className="stat-heading"><span>Monthly budget</span><Wallet size={17} /></div><strong>{formatMoney(2400)}</strong><div className="stat-foot"><span>{formatMoney(Math.max(0, 2400 - totalSpent))} left to spend</span></div><div className="budget-bar"><span style={{ width: `${Math.min(100, (totalSpent / 2400) * 100)}%` }} /></div><small>{Math.round((totalSpent / 2400) * 100)}% of your budget used</small></div><div className="stat-card"><div className="stat-heading"><span>Avg. daily spend</span><ArrowUpRight size={17} /></div><strong>{formatMoney(totalSpent / 24)}</strong><div className="stat-foot"><span className="positive">↓ 3.1%</span> <span>vs last month</span></div><div className="mini-bars">{Array.from({ length: 10 }, (_, index) => <i key={index} />)}</div></div></div>
        <div className="dashboard-grid"><section className="panel transactions-panel" id="transactions"><div className="panel-heading"><div><h2>Recent transactions</h2><p>Your latest spending, all in one place.</p></div><button className="text-button">View all <ArrowUpRight size={15} /></button></div><div className="transaction-list">{filteredExpenses.slice(0, 5).map((expense) => <div className="transaction" key={expense.id}><span className={`expense-icon ${expense.color}`}>{expense.icon}</span><div className="transaction-info"><strong>{expense.title}</strong><span>{expense.category} · {new Date(`${expense.date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</span></div><strong className="amount">-{formatMoney(expense.amount)}</strong><button className="delete-button" onClick={() => setExpenses(expenses.filter((item) => item.id !== expense.id))} aria-label={`Delete ${expense.title}`}><Trash2 size={15} /></button></div>)}</div>{filteredExpenses.length === 0 && <div className="empty-state">No expenses match your search.</div>}<button className="add-row" onClick={() => setIsModalOpen(true)}><Plus size={16} /> Add a transaction</button></section><section className="panel breakdown-panel" id="insights"><div className="panel-heading"><div><h2>Spending breakdown</h2><p>Where your money is going.</p></div><button className="more-button" aria-label="More options">•••</button></div><div className="donut-wrap"><div className="donut"><div><strong>{formatMoney(totalSpent)}</strong><span>this month</span></div></div></div><div className="category-list">{categories.map((category) => <div className="category-row" key={category.name}><span className="category-dot" style={{ background: category.color }} /><span>{category.name}</span><strong>{formatMoney(category.amount)}</strong><small>{category.percent}%</small></div>)}</div></section></div><section className="tip-banner"><div className="tip-icon"><Sparkles size={20} /></div><div><strong>A little win goes a long way</strong><p>You&apos;re spending 8.4% less than last month. Keep it up, you&apos;re building a great habit.</p></div><button className="close-tip" aria-label="Close tip"><X size={16} /></button></section><footer>Made for calmer money days <span>·</span> Last synced just now</footer></div></section>
    {isModalOpen && <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={addExpense}><div className="modal-heading"><div><p className="eyebrow">New transaction</p><h2>Add an expense</h2></div><button type="button" className="icon-button" onClick={() => setIsModalOpen(false)} aria-label="Close"><X size={18} /></button></div><label>What was it for?<input autoFocus value={newExpense.title} onChange={(event) => setNewExpense({ ...newExpense, title: event.target.value })} placeholder="e.g. Grocery run" /></label><div className="form-row"><label>Amount<input type="number" min="0" step="0.01" value={newExpense.amount} onChange={(event) => setNewExpense({ ...newExpense, amount: event.target.value })} placeholder="0.00" /></label><label>Date<input type="date" value={newExpense.date} onChange={(event) => setNewExpense({ ...newExpense, date: event.target.value })} /></label></div><label>Category<select value={newExpense.category} onChange={(event) => setNewExpense({ ...newExpense, category: event.target.value })}>{["Food & dining", "Housing", "Transport", "Subscriptions", "Other"].map((category) => <option key={category}>{category}</option>)}</select></label><div className="modal-actions"><button type="button" className="button-secondary" onClick={() => setIsModalOpen(false)}>Cancel</button><button type="submit" className="button-primary"><Plus size={16} /> Save expense</button></div></form></div>}
  </main>;
}
